#!/usr/bin/bash

event_type=EV_KEY
action_type=POINTER_AXIS 
scrolled="horiz"

readarray -t devices <<<$(libinput list-devices | grep pointer -B3 | grep -o '/dev/input/event[1-9]*') 

# COMMANDS MAP
HWHEEL_UP=(KEY_VOLUMEUP)
HWHEEL_DOWN=(KEY_VOLUMEDOWN)

function pressKey(){
    device=$1; key=$2
    evemu-event /dev/input/${device} --sync --type ${event_type} --code ${key} --value 1;
    evemu-event /dev/input/${device} --sync --type ${event_type} --code ${key} --value 0;
}

function pressCommand(){
    device=$1; wheel=$2; movement=$3
    if [ ${wheel} = ${scrolled} ]; then
        if [ ${movement} -gt 0 ]; then
            pressKey ${device} ${HWHEEL_UP}
        else
            pressKey ${device} ${HWHEEL_DOWN}
        fi
    fi
}

function parseEventLine(){
    device=$1
    action=$2
    wheel=$6
    movement=${7%%.*}
    # compute only if right action
    if [ ${action} = ${action_type} ] && [ ${movement} -ne 0 ]; then
        pressCommand ${device} ${wheel} ${movement}
    fi
}

function mapDevice(){
    device=$1
    while read line; do
        parseEventLine ${line}
    done < <(stdbuf -oL libinput debug-events --device ${device} & )
}

for device in ${devices[@]}; do
    ( mapDevice ${device} ) &
done

wait
